version: 2

models:
  - name: stg_infinity_works__customers
    description: ""
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
        tests:
          - unique
          - not_null


      - name: loyalty_score
        description: "Customer loyalty score."


  - name: stg_infinity_works__products
    description: ""
    columns:
      - name: product_id
        description: "Unique identifier for the product."

      - name: product_description
        description: ""

      - name: product_category
        description: ""


  - name: stg_infinity_works__transactions
    description: ""
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."

      - name: purchased_at
        description: "The date and time of the transaction/purchase."

      - name: basket_items
        description: ""