--Final table, with the required output
CREATE OR REPLACE TABLE CONVEX_DB.INPUT_DATA.FINAL_TABLE 
AS
(
select distinct T.CUSTOMER_ID
,C.LOYALTY_SCORE
,T.PRODUCT_ID
,P.PRODUCT_CATEGORY
,COUNT(1) AS PRODUCT_COUNT
FROM  "CONVEX_DB"."INPUT_DATA"."TRANSACTIONS_FINAL_TBL" t
INNER JOIN "CONVEX_DB"."INPUT_DATA"."PRODUCTS_TBL" P
ON T.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN "CONVEX_DB"."INPUT_DATA"."CUSTOMERS_TBL" C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
WHERE 1=1
GROUP BY 1,2,3,4
ORDER BY 5 DESC
);
