--New File Format 
CREATE OR REPLACE FILE FORMAT "CONVEX_DB"."INPUT_DATA".json_format
TYPE = 'JSON' 
COMPRESSION = 'AUTO' 
STRIP_OUTER_ARRAY = FALSE ;


CREATE OR REPLACE  TABLE CONVEX_DB.INPUT_DATA.TRANSACTIONS_FINAL_TBL
AS
(
SELECT  
TRANS_JSON:customer_id::string AS CUSTOMER_ID 
,TRANS_JSON:date_of_purchase::datetime AS PURCHASE_DATE 
,VALUE:price::float AS PRICE
,VALUE:product_id::string as PRODUCT_ID
FROM "CONVEX_DB"."INPUT_DATA"."TRANSACTIONS_BASE_TBL" t
JOIN lateral flatten( input => TRANS_JSON:basket ) 
)
