CREATE OR REPLACE VIEW REP_SCHEMA.CUSTOMERS_COSTUME AS(
  SELECT  c.CUSTOMER_ID CUSTOMER_ID
         ,c.LOYALTY_SCORE LOYALTY_SCORE
         ,p.PRODUCT_ID PRODUCT_ID
         ,p.PRODUCT_CATEGORY PRODUCT_CATEGORY
         ,count(*) purchase_count
  FROM SRC_SCHEMA.TRANSACTIONS_JSON_BUCKET_PARSED bp
  INNER JOIN 
  SRC_SCHEMA.CUSTOMERS c
  ON bp.customer_id = c.customer_id
  INNER JOIN 
  SRC_SCHEMA.PRODUCTS p
  ON bp.PRODUCT_ID = p.PRODUCT_ID
  GROUP BY c.CUSTOMER_ID, c.LOYALTY_SCORE, p.PRODUCT_ID, p.PRODUCT_CATEGORY
  )