name: 'infinity_works'
version: 1.0.0

config-version: 2

profile: 'default'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
    infinity_works:
      materialized: table
      staging:
        materialized: view
        tags: ["staging"]